version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - me_alone_network
    volumes:
      - /home/alti100/nginx.conf:/etc/nginx/nginx.conf
      - me_alone_static:/data/static/
      - me_alone_media:/data/media/

  django:
    image: me_alone_django:4
    networks:
      - me_alone_network
    volumes:
      - me_alone_static:/home/me_alone/staticfiles/
      - me_alone_media:/home/me_alone/media/
    secrets:
      - DjangoSecretKey

  mariadb:
    image: mariadb:10.5
    networks:
      - me_alone_network
    volumes:
      - me_alone_mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password1234
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234

networks:
  me_alone_network:

volumes:
  me_alone_static:
  me_alone_media:
  me_alone_mariadb:

secrets:
  DjangoSecretKey:
    external: true