version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80
    networks:
      - me_alone_network
    volumes:
      - /home/alti100/nginx.conf:/etc/nginx/nginx.conf
      - me_alone_static:/data/static/
      - me_alone_media:/data/media/
      - me_alone_log:/var/log/nginx/
    secrets:
      - NGINX_AUTH
  goaccess:
    image: allinurl/goaccess:1.5.1
    ports:
      - 7890:7890
    volumes:
      - me_alone_log:/var/log/nginx/
    command: /var/log/nginx/me_alone_access.log -o /var/log/nginx/report.html --real-time-html --log-format COMBINED

  django:
    image: me_alone_django:5
    networks:
      - me_alone_network
    volumes:
      - me_alone_static:/home/me_alone/staticfiles/
      - me_alone_media:/home/me_alone/media/
    secrets:
      - DjangoSecretKey
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - me_alone_network
    volumes:
      - me_alone_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_ROOT_PASSWORD
      - MARIADB_USER
      - MARIADB_PASSWORD
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD

networks:
  me_alone_network:

volumes:
  me_alone_static:
  me_alone_media:
  me_alone_mariadb:
  me_alone_log:

secrets:
  DjangoSecretKey:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  NGINX_AUTH:
    external: true